version: "3.4"
services:
  nginx:
    build: './Docker/nginx/'
    depends_on:
      - php
      - mysql
    networks:
      - backend
    ports:
      - '${NGINX_PORT}:80'
    volumes:
      - ./source:/var/www/html/
    container_name: phuctt-nginx
    restart: always
  php:
    build:
      context: './Docker/php/'
      target: php
    networks:
      - backend
    volumes:
      - ./source:/var/www/html/
      - ./Docker/php/config/config.ini:/usr/local/etc/php/conf.d/uploads.ini
    container_name: phuctt-php
    restart: always
<<<<<<< HEAD

=======
>>>>>>> 1492790719a223a10d76321bb456a6b789e51d7c
    user: phuc:phuc
  mysql:
    image: mysql
    volumes:
      - ./source:/var/www/html/
    networks:
      - backend
    ports:
      - '${DB_CONTAINER_PORT}:3306'
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    container_name: phuctt-mysql
    restart: always

networks:
  backend:
  