version: "3.4"
services:
  nginx:
    build: './Docker/nginx/'
    depends_on:
      - php
      - mysql
    networks:
      - backend
    ports:
      - '90:80'
    restart: always
  php:
    build:
      context: './Docker/php/'
      target: php
    networks:
      - backend
    volumes:
      - ./Docker/php/config/config.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always
  mysql:
    image: mysql
    networks:
      - backend
    ports:
      - '3309:3300'
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'miichi'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    restart: always

networks:
  backend:
  