version: "3.4"
services:
  php:
    build:
      context: './Docker'
      dockerfile: Dockerfile
    networks:
      - backend
    volumes:
      - ./:/var/www/html/
  nginx:
    build: './Docker/nginx/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - '8020:80'
    volumes:
      - ./source/:/var/www/html/

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '8000:3306'
    networks:
      - backend
    volumes:
      - ./:/var/www/html/
    environment:
      MYSQL_DATABASE: 'enport_work'
      MYSQL_USER: 'sail'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
networks:
  frontend:
  backend: